# use docker network create --subnet=10.53.1.0/24 docker_ran
# to create the network first
# "Config": [
#     {
#         "Subnet": "10.53.1.0/24",
#         "Gateway": "10.53.1.1"
#     }

networks:
  docker_ran:
    external: true

services:
  srs5ggNB:
    image: its-registry.unl.edu/nextt/runtime/srsran-4g/amd64/uhd_master:main-df286439
    # image: pavonis/srs-gnb-dev
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /lib/modules:/lib/modules
      - /etc/network:/etc/network:rw
      - ./configs:/home/ubuntu/configs/
      - ./scripts:/home/ubuntu/scripts/
    tty: true
    networks:
      docker_ran:
        ipv4_address: 10.53.1.3
    # command: >
    #   bash -c "
    #     bash /home/ubuntu/scripts/gNB_script.sh &&
    #     gnb -c /home/ubuntu/configs/gnb_fromgithubIssues.yml &&
    #     bash"
    command: >
      bash -c "
        source sudo su &&
        bash /home/ubuntu/scripts/gNB_script.sh &&
        gnb -c /home/ubuntu/configs/gnb_rf_b200_tdd_n78_20mhz.yml &&
        bash"

#epc command
#docker run --net docker_ran --ip 10.53.1.2 --env-file open5gs.env --privileged --publish 9999:9999 --publish 38412:38412/sctp --publish 2152:2152/udp open5gs-docker ./build/tests/app/5gc -c open5gs-5gc.yml
