networks:
  docker_ran:
    external: true

services:
  srs5ggNB:
    image: its-registry.unl.edu/nextt/runtime/srsran-4g/amd64/uhd_master:main-df286439
    # image: pavonis/srs-gnb-dev
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /lib/modules:/lib/modules
      - /etc/network:/etc/network:rw
      - ./configs:/home/ubuntu
      - ./gNB_pcap:/tmp
    tty: true
    networks:
      docker_ran:
        ipv4_address: 10.53.1.3
    user: root
    # command: >
    #   bash -c "
    #     bash /home/ubuntu/gNB_script.sh &&
    #     sudo gnb -c /home/ubuntu/gnb_rf_b210_fdd_srsUE.yml &&
    #     bash"
    # command: >
    #   bash -c "
    #     bash /home/ubuntu/gNB_script.sh &&
    #     gnb -c /home/ubuntu/gnb_rf_b200_tdd_n78_20mhz.yml &&
    #     bash"

# bash /home/ubuntu/gNB_script.sh && gnb -c /home/ubuntu/gnb_rf_b210_fdd_srsUE.yml
# bash /home/ubuntu/gNB_script.sh && gnb -c /home/ubuntu/gnb_rf_b200_tdd_n78_20mhz.yml