networks:
  core_network_5G:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: corenet5G_dev
    ipam:
      driver: default
      config:
        - subnet: 11.53.1.0/24
          gateway: 11.53.1.1

services:
  5gc:
    image: its-registry.unl.edu/cpn/doe-xgfabric-repos/srsran-5g/open5gs-docker
    env_file:
      - ${OPEN_5GS_ENV_FILE:-configs/open5gs.env}
    privileged: true
    volumes:
      - ./configs/set_slices.sh:/open5gs/set_slices.sh
      - ./configs/add-user-slices.py:/open5gs/add-user-slices.py
      - ./configs/open5gs-5gc.yml.in.slicing:/open5gs/open5gs-5gc.yml.in
      - ./configs/subscriber_db.csv:/open5gs/subscriber_db.csv
      - ./configs/startcore.sh:/open5gs/startcore.sh
    ports:
      - "9998:9999/tcp"
      - "38413:38412/sctp"
      - "2153:2152/udp"
    command: ["./startcore.sh"]
    networks:
      core_network_5G:
        ipv4_address: ${OPEN5GS_IP:-11.53.1.2}

  gnb:
    image: its-registry.unl.edu/nextt/runtime/srsran-4g/amd64/srs5g-gnb_latest
    privileged: true
    depends_on:
      - 5gc
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /lib/modules:/lib/modules
      - /etc/network:/etc/network:rw
      - ./configs:/home/ubuntu
      - ./pcap:/tmp
    tty: true
    networks:
      core_network_5G:
        ipv4_address: 11.53.1.3
    user: root
    command: >
      bash -c "
        sleep 4 &&
        bash /home/ubuntu/gNB_script.sh &&
        gnb -c /home/ubuntu/experiment-w-slicing-1.yml
        #gnb -c /home/ubuntu/gnb_works.yml &&
        #gnb -c /home/ubuntu/gnb_better_throughput.yml &&
        # gnb -c /home/ubuntu/gnb_works.yml -c /home/ubuntu/mimo.yml &&
        bash"
