# This example configuration outlines how to configure the srsRAN Project gNB to create a single FDD cell
# transmitting in band 3, with 20 MHz bandwidth and 15 kHz sub-carrier-spacing. A USRP B200 is configured
# as the RF frontend using split 8, with a Leo Bodnar GPSDO as an external reference clock.

# This particular configuration is intended to be used with srsUE. Note the `pdcch` parameters set in the
# `cell_cfg` section. These are set to match the capabilities of srsUE.

#same file as srsRAN_Project -> USE only FOR srsUE
cu_cp:
  amf:
    addr: 10.53.1.2
    port: 38412
    bind_addr: 10.53.1.3
    supported_tracking_areas:
      - tac: 7
        plmn_list:
          - plmn: "00101"
            tai_slice_support_list:
              - sst: 1

ru_sdr:
  device_driver: uhd                # The RF driver name.
  device_args: type=b200,num_recv_frames=64,num_send_frames=64            # Optionally pass arguments to the selected RF driver.
  clock: external
  #sync: internal 
  srate: 5.76                      # RF sample rate might need to be adjusted according to selected bandwidth.
  tx_gain: 80                       # Transmit gain of the RF might need to adjusted to the given situation.
  rx_gain: 50                       # Receive gain of the RF might need to adjusted to the given situation.

cell_cfg:
  dl_arfcn: 368500                  # ARFCN of the downlink carrier (center frequency).
  band: 3                           # The NR band.
  channel_bandwidth_MHz: 5         # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 15                    # Subcarrier spacing in kHz used for data.
  plmn: "00101"                     # PLMN broadcasted by the gNB.
  tac: 7                            # Tracking area code (needs to match the core configuration).
  nof_antennas_ul: 1
  nof_antennas_dl: 1
  pdcch:
    common:
      ss0_index: 0                  # Set search space zero index to match srsUE capabilities
      #coreset0_index: 12            # Set search CORESET Zero index to match srsUE capabilities
    dedicated:
      ss2_type: common              # Search Space type, has to be set to common
      dci_format_0_1_and_1_1: false # Set correct DCI format (fallback)
  prach:
    prach_config_index: 1           # Sets PRACH config to match what is expected by srsUE
  pucch:
    f0_or_f1_nof_cell_res_sr: 2
    f2_or_f3_or_f4_nof_cell_res_csi: 2
  pdsch:
    mcs_table: qam64
  pusch:
    mcs_table: qam64

# ru_sdr:
#   device_driver: uhd
#   device_args: type=b200
#   clock: external
#   srate: 23.04
#   tx_gain: 80
#   rx_gain: 50

# cell_cfg:
#   dl_arfcn: 368500
#   band: 3
#   channel_bandwidth_MHz: 15
#   common_scs: 15
#   plmn: "00101"
#   # nof_antennas_ul: 1
#   # nof_antennas_dl: 1
#   tac: 7
#   pdcch:
#     dedicated:
#       ss2_type: common
#       dci_format_0_1_and_1_1: false
#     common:
#       ss0_index: 0
#       coreset0_index: 12
#   prach:
#     prach_config_index: 1
#   pdsch:
#     mcs_table: qam64
#   pusch:
#     mcs_table: qam64

log:
  filename: /tmp/gnb.log
  all_level: info

pcap:
  mac_enable: true
  mac_filename: /tmp/gnb_mac.pcap
  ngap_enable: true
  ngap_filename: /tmp/gnb_ngap.pcap
